---
title: "Stock Market Prediction"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    runtime: shiny
    vertical_layout: scroll
---

```{r setup, include=FALSE}
#install.packages("pdfetch")
library(flexdashboard)
library(quantmod)
library(prophet)
library(pdfetch)
library(dygraphs)
library(plotly)
```

```{r }

MinMaxScaling <- function(x){
  return((x-min(x))/(max(x)-min(x)))
}

zscorestd <- function(x){
  return((x-mean(x))/sd(x))
}

stock_data <- reactive({
  withProgress({
        setProgress(message = "Getting Data...")
  ip <- input$stock_id
  sdata <- pdfetch_YAHOO(ip)
  #s <- MinMaxScaling(sdata[,6])
  s <- log(sdata[,4])
  Date <- row.names(as.data.frame(as.xts(sdata)))
  d <- data.frame(as.POSIXct(Date),as.character(s))
  row.names(d) <- c()
  names(d)[1] <- "ds"
  names(d)[2] <- "y"
  return(d)
    })
  })
  
```

Sidebar {.sidebar}
=====================================

```{r}

textInput("stock_id", "Enter Stock ID here", "GOOGL")

```

Main Page
===========================


### Stock Prices

```{r}
renderDygraph({
  withProgress(message = "Loading Predictions...", {
  sd <- stock_data()  
  n <- prophet(sd)
  future <- make_future_dataframe(n,periods = 365)
  forecast <- predict(n,future)
  dyplot.prophet(n,forecast)
 })
})


```

Components of Time series
===================================


### Overall Trend 

```{r}
renderPlot({
  withProgress(message = "Loading ...", {
  sd <- stock_data()  
  n <- prophet(sd)
  future <- make_future_dataframe(n,periods = 365)
  forecast <- predict(n,future)
  p <- prophet_plot_components(n,forecast)
  p[1]
  })
})
```

Row
-----------------------------------


### Weekly Trend 

```{r}
renderPlot({
  withProgress(message = "Loading ...", {
  sd <- stock_data()  
  n <- prophet(sd)
  future <- make_future_dataframe(n,periods = 365)
  forecast <- predict(n,future)
  p <- prophet_plot_components(n,forecast)
  p[2]
  })
})
```


Row
--------------------------------------

### Yearly Trend 

```{r}
renderPlot({
  withProgress(message = "Loading ...", {
  sd <- stock_data()  
  n <- prophet(sd)
  future <- make_future_dataframe(n,periods = 365)
  forecast <- predict(n,future)
  p <- prophet_plot_components(n,forecast)
  p[3]
  })
})
```


Summary
========================
  
```{r}
renderPrint({
  withProgress(message = "Loading ...", {
  sd <- stock_data()  
  n <- prophet(sd)
  future <- make_future_dataframe(n,periods = 365)
  forecast <- predict(n,future)
  pred <- forecast$yhat[1:nrow(sd)]
  actual <- n$history$y
  a <- summary(lm(pred~actual))
  a
  })
})
```



About Report
========================================

Created by: Vignesh EA

Confidential: Nothing like that!






